version: "3"
networks:
  backend: null
  frontend:
    external: true
    name: app-traefik-${ENV}_backend
        
services:
  mysql:
    image: mysql
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=${MySQL_Password}
    volumes:
      - ./data/db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - backend
    
