/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [cDealer ID]
      ,[stDealer Name]
      ,[stDealer Description]
      ,[stDealer Address Number/Name]
      ,[stDealer Address Line1]
      ,[stDealer Address Line2]
      ,[stDealer Address Town/City]
      ,[stDealer Address County]
      ,[stDealer Address Postal Code]
      ,[stDealer Telephone Number]
      ,[stDealer Fax Number]
      ,[stDealer E-Mail Address]
      ,[Franchise]
      ,[yDealer Hide]
      ,[CCL]
      ,[Terms]
      ,[Info]
      ,[Dealer Status]
      ,[cExecutive ID]
      ,[CCLExpireDate]
      ,[DealerComment]
      ,[DealerCustContact]
      ,[DealerDefaultContact]
      ,[DealerDisallowedFunder]
      ,[DealerSite]
      ,[DealerGroup]
      ,[DealerFSAAuthorisationNumber]
      ,[DealerFSAAuthorisation]
      ,[DealerCommissionSortcode]
      ,[DealerCommissionAccountNumber]
      ,[DealerCommissionAccountName]
      ,[DealerAdvancesSortcode]
      ,[DealerAdvancesAccountNumber]
      ,[DealerAdvancesAccountName]
      ,[DealerGroupID]
      ,[upsize_ts]
      ,[IsFranchisedDealer]
      ,[IsFranchised]
      ,[OfficeID]
      ,[RegisteredTradingName]
      ,[stDealer Address Name]
      ,[stDealer Address Line3]
      ,[FCAAuthTypeID]
      ,[FCAPermissions]
      ,[FCAApplicationDeadline]
      ,[FCAApplicationMade]
      ,[FCAApplicationApproved]
      ,[FCAPrincipalFirm]
      ,[MaxAutoSendProducts]
      ,[FunderLadderID]
      ,[DateAdded]
      ,[DateUpdated]
      ,[UpdatedBy]
      ,[AddedBy]
      ,[StandardTradingName]
      ,[ContactName]
      ,[DefaultSalesProcessID]
      ,[StatusChangeDate]
      ,[StatusChanger]
  FROM [MaiaDSG].[dbo].[tDealer]
  where (DealerGroupID = 221 or DealerGroupID = 256) and (DefaultSalesProcessID != 11) and ([Dealer Status] = 1)