/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [ExecutiveGroupID]
      ,[ExecutiveGroupName]
      ,[ExecutiveGroupDescription]
      ,[ExecutiveGroupAddress Number/Name]
      ,[ExecutiveGroupAddress Line1]
      ,[ExecutiveGroupAddress Line2]
      ,[ExecutiveGroupAddress Town/City]
      ,[ExecutiveGroupAddress County]
      ,[ExecutiveGroupAddress Postal Code]
      ,[ExecutiveGroupTelephone Number]
      ,[ExecutiveGroupFax Number]
      ,[ExecutiveGroup E-Mail Address]
      ,[ExecutiveGroupHide]
      ,[upsize_ts]
      ,[ExecutiveGroupIsGeoTerritory]
      ,[IsBMGroup]
      ,[IsTerritoryGroup]
  FROM [MaiaDSG].[dbo].[tblExecutiveGroup]