/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [ID]
      ,[ExternalProposalID]
      ,[SubmissionDateTime]
      ,[RetrievalDateTime]
      ,[CustomerSurname]
      ,[CustomerForename]
      ,[CustomerDateOfBirth]
      ,[CustomerPostCode]
      ,[ApplicationXML]
      ,[CROWSSearchID]
      ,[CREWSSearchEvaluatedID]
      ,[AppApproved]
      ,[DecisionStatusID]
      ,[FundersPassed]
      ,[FundersNotPassed]
      ,[LatestStageID]
      ,[ReferrerID]
      ,[DateTimeStarted]
      ,[DealerID]
      ,[ExecutiveID]
      ,[SystemID]
      ,[SystemName]
      ,[Salesman]
      ,[EntityID]
  FROM [AbsoluteLeads].[dbo].[tblApplications]
  where DecisionStatusID = 4