/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [cExecutive ID]
      ,[ExecutiveGroupID]
      ,[stExecutive Name]
      ,[stExecutive Description]
      ,[stExecutive Address Number/Name]
      ,[stExecutive Address Line1]
      ,[stExecutive Address Line2]
      ,[stExecutive Address Town/City]
      ,[stExecutive Address County]
      ,[stExecutive Address Postal Code]
      ,[stExecutive Telephone Number]
      ,[stExecutive Fax Number]
      ,[stExecutive E-Mail Address]
      ,[yExecutive Hide]
      ,[stExecutive Update]
      ,[ExecDefaultContact]
      ,[ExecutiveFSAAuthorisationNumber]
      ,[ExecutiveFSAAuthorisation]
      ,[upsize_ts]
      ,[ActiveAccountManagerID]
      ,[ExecUserID]
      ,[IncludeInPerLeagueReport]
      ,[IncludeInPerfLeagueReport]
      ,[IsInternal]
      ,[ShortName]
      ,[DealerFriendlyName]
      ,[SkillLevel]
      ,[EnrolIn3AP]
      ,[EligibleFor3AP]
      ,[IsTerritory]
      ,[IsBusinessManager]
      ,[ExcludeFromReportsWhenFilteredByTerritory]
      ,[LowestSkillLevelToWork]
  FROM [MaiaDSG].[dbo].[tExecutive]
  where [stExecutive Name] in ('CCF Birmingham','ccf south mids')