version: '3'
networks:
  backend: null

services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.directory=/configuration/"
      - "--providers.file.watch=true"
      - "--serverstransport.insecureskipverify=true"
    ports:
      - "80:80"
      - "443:443"
    labels:
      - traefik.enable=true
      - traefik.backend=frontend
      - traefik.docker.network=app-traefik-${ENV}_backend
      - traefik.http.routers.traefik.rule=Host(`traefik.${ENV}.epichouse.co.uk`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.routers.traefik.tls=true
    volumes:
      - /etc/ssl:/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/config/:/configuration/
    networks:
      - backend